name: thebleep
version: stable
version-script: git -C parts/thebleep/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Bleep tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  thebleep:
    command: bin/thebleep
    environment:
        PYTHONIOENCODING: utf-8
  bleep:
    command: bin/bleep
    environment:
        PYTHONIOENCODING: utf-8

parts:
  thebleep:
    source: https://github.com/stamparm/thebleep.git
    plugin: python
