# -*- encoding: utf-8 -*-

"""How often the first suggestion is the right one.

    python3 bench/hit_rate.py             # the table
    python3 bench/hit_rate.py --compare   # ...beside The Fuck 3.32
    python3 bench/hit_rate.py --record    # ...and write it to results/

`--compare` needs `thefuck` importable, which needs Python 3.11 or older -- it
does not start on 3.12. That is why the comparison is recorded rather than run
in CI. `bench/README.md` says how the environment was built.

The only number in this space anybody has bothered to measure. A correction tool
is judged by whether the *first* answer is right -- that is the one enter runs --
and until now nothing here could say. The claim in the README is this script's
output, recorded against a named commit, the same discipline as the benchmark
next to it.

It measures the corpus, which is real typos with real tool output and a fixed
`PATH`, so the number does not move when it is run on a different machine. See
`tests/corpus/README.md`.

What it cannot tell you: whether the corpus is representative. It is a few
hundred cases chosen and generated by the people who wrote the tool, not a
sample of what the world types. A rising number means the cases that are in it
pass; it is not a claim about all typos everywhere, and saying so is part of the
point of publishing it.

"""

from __future__ import print_function

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)


GROUPS = ('an unknown program', 'the tool said so', 'nothing is right')


def _measure(package='thebleep'):
    """The corpus, run through `package`'s corrector, grouped.

    Both tools are asked the identical question -- the same script, the same
    captured output, the same `PATH`, the same history -- because the point is
    the comparison and anything else makes it meaningless. The architecture is
    the same in both, which is what lets one function do it.

    """
    import importlib
    from unittest import mock

    conf = importlib.import_module(package + '.conf')
    corrector = importlib.import_module(package + '.corrector')
    utils = importlib.import_module(package + '.utils')
    types = importlib.import_module(package + '.types')
    Command = types.Command

    from tests.corpus import cases

    conf.settings.init()
    names = _executables()
    installed = set(names)

    def which(name):
        return ('/usr/bin/' + name
                if os.path.basename(name) in installed else None)

    groups = list(zip(GROUPS, (cases.NO_SUCH_PROGRAM,
                               cases.THE_TOOL_SAID_SO,
                               cases.NOTHING_IS_RIGHT)))

    results = []
    with mock.patch.object(utils.memoize, 'disabled', True), \
            mock.patch(package + '.utils.get_all_executables',
                       return_value=names), \
            mock.patch(package + '.utils.get_valid_history_without_current',
                       return_value=cases.HISTORY), \
            mock.patch(package + '.utils.which', side_effect=which):
        for label, group in groups:
            hits = 0
            misses = []
            for script, output, expect in group:
                try:
                    corrected = list(corrector.get_corrected_commands(
                        Command(script, output)))
                except Exception:
                    # The Fuck lets a rule's exception out of the corrector,
                    # which is one of the differences being measured.
                    corrected = []
                first = corrected[0].script if corrected else None
                if first == expect:
                    hits += 1
                else:
                    misses.append((script, expect, first))

            results.append((label, hits, len(group), misses))

    return results


def _executables():
    with open(os.path.join(ROOT, 'tests', 'corpus', 'executables.txt')) as f:
        return [line.strip() for line in f if line.strip()]


def _commit():
    def git(*arguments):
        try:
            return subprocess.run(['git'] + list(arguments), cwd=ROOT,
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.DEVNULL).stdout \
                .decode('utf-8', 'replace').strip()
        except OSError:
            return ''

    return git('rev-parse', 'HEAD'), git('status', '--porcelain') == ''


def _totals(results):
    return (sum(hits for _, hits, _, _ in results),
            sum(count for _, _, count, _ in results))


def main():
    results = _measure()
    total_hits, total = _totals(results)

    other = None
    if '--compare' in sys.argv:
        try:
            other = _measure('thefuck')
        except ImportError:
            print('thefuck is not importable here; skipping the comparison.',
                  file=sys.stderr)

    print()
    if other:
        other_hits, _ = _totals(other)
        print('| what is being asked | The Bleep | The Fuck 3.32 |')
        print('| --- | --- | --- |')
        for (label, hits, count, _), (_, theirs, _, _) in zip(results, other):
            print('| {} | **{}/{}** | {}/{} |'.format(
                label, hits, count, theirs, count))
        print('| **all of it** | **{}/{} ({:.0f}%)** | {}/{} ({:.0f}%) |'.format(
            total_hits, total, 100.0 * total_hits / total,
            other_hits, total, 100.0 * other_hits / total))
    else:
        print('| what is being asked | first answer right |')
        print('| --- | --- |')
        for label, hits, count, _ in results:
            print('| {} | {}/{} |'.format(label, hits, count))
        print('| **all of it** | **{}/{}  ({:.0f}%)** |'.format(
            total_hits, total, 100.0 * total_hits / total))
    print()

    for label, _, _, misses in results:
        for script, expect, first in misses:
            print('  miss  {:<28} wanted {!r}, got {!r}'.format(
                script, expect, first))

    commit, clean = _commit()
    if '--record' not in sys.argv:
        return 0 if total_hits == total else 1

    if not clean:
        print('Refusing to record a run from a tree with changes in it.',
              file=sys.stderr)
        return 2

    recorded = {
        'environment': {'commit': commit, 'working_tree_clean': clean},
        'groups': [{'what': label, 'hits': hits, 'of': count}
                   for label, hits, count, _ in results],
        'total': {'hits': total_hits, 'of': total},
    }
    if other:
        recorded['thefuck_3_32'] = {
            'groups': [{'what': label, 'hits': hits, 'of': count}
                       for label, hits, count, _ in other],
            'total': {'hits': _totals(other)[0], 'of': total},
        }
    where = os.path.join(HERE, 'results', 'hit-rate.json')
    with open(where, 'w') as handle:
        json.dump(recorded, handle, indent=2, sort_keys=True)
        handle.write('\n')

    print('recorded to', where)
    return 0


if __name__ == '__main__':
    sys.exit(main())
